### ISSUE TITLE
Recipes using prefect-sqlalchemy collection

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect-recipes#149]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Showcase using SQLAlchemy in your workflow

https://prefecthq.github.io/prefect-sqlalchemy/

### Describe the solution you'd like

One or more recipes

### Describe alternatives you've considered

n/a

**Comment by sidharth1805** [comment]
@serinamarie have created a PR for this recipe let me know if it's fine 🙂.
