### ISSUE TITLE
[Bug]: Image in rendered docs page shows as broken

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect-recipes#175]
### 💻

- [ ] Would you like to work on a fix?

### Current behavior

See screen shot below
![Screen Shot 2022-11-17 at 4 52 24 PM](https://user-images.githubusercontent.com/7703961/202567695-f75441bf-b029-4e47-833c-5816dc36e280.png)

### Expected behavior

The image displays. Screen shot from README on GitHub below.

![Screen Shot 2022-11-17 at 4 54 03 PM](https://user-images.githubusercontent.com/7703961/202567988-fa79717d-a96b-412c-abb8-96ed93d306d1.png)

### Possible solution

Not sure why it doesn't work - it renders okay on README on GitHub. I added `./` to the image path in PR #174. I have seen something similar work to get images to render in some MarkDown environemnt.

**Comment by discdiver** [comment]
btw, the page isn't editable if you click on the pencil, but I think I raised that issue before in the main repo and there wasn't an easy fix. 🙂

**Comment by serinamarie** [comment]
Thanks @discdiver ! Let's try your solution. And yeah, I don't believe there is an easy fix for the appearance of the pencil.

**Comment by serinamarie** [comment]
hm, it still isn't rendering correctly. maybe @ahuang11 has another idea?

**Comment by discdiver** [comment]
Closing as we are just sending people to the README page on GH (https://prefecthq/github.io/prefect-recipes is not built)
