### ISSUE TITLE
[Bug]: Broken link in README.md for Dockerfiles example

### ISSUE THREAD

**Issue by Creep-ai** [PrefectHQ/prefect-recipes#182]
### 💻

- [ ] Would you like to work on a fix?

### Current behavior

Broken link here https://github.com/PrefectHQ/prefect-recipes/blob/main/README.md#dockerfiles
It's redirecting on 404 page

### Expected behavior

Link should works or that list item should be deleted

**Comment by zzstoatzz** [comment]
Hi @Creep-ai -- sorry about this!

We removed this dead link last week in #213

Let us know if you'd like to see a specific dockerfile related recipe
