### ISSUE TITLE
A configuraiton to run on Kubernetes without external Prefect Cloud connection

### ISSUE THREAD

**Issue by PetrGlad** [PrefectHQ/prefect-recipes#230]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

All configuration variants seem to require cloud account id. It does not seem like it is really open source.
If this is not something the authors of Prefect want, at the very least it should be stated upfront in the introductory documentation.

### Describe the solution you'd like

A Helm chart I can use in on-premise Kubernetes cluster without any external connections.
The helm chart should configure necessary permissions for a prefect container to initiate workflow steps.

### Describe alternatives you've considered

Already using Argo, hoped to find a simpler solution for our needs.

**Comment by jamiezieziula** [comment]
Hi @PetrGlad - are you looking to deploy prefect server on your own cluster? If so - the helm chart for that is [here](https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-server)

**Comment by PetrGlad** [comment]
@jamiezieziula Thanks! Will try it out.
